# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Matteo Testa
tagline:          'Machine learning research engineer'
description:      'Machine Learning research engineer @ Unicredit'
url:              https://www.matteotesta.it
baseurl:          https://www.matteotesta.it/

author:
  name:           'Matteo Testa'
  url:            https://www.matteotesta.it

paginate:         5

# Custom vars
version:          0.0.9

github:
  repo:           https://github.com/poole/hyde
  googleAnalytics: UA-120466923-1


