# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Matteo Testa
tagline:          'A Jekyll theme'
description:      'Machine Learning research engineer @ Unicredit R&D group.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Matteo Testa'
  url:            https://www.matteotesta.it

paginate:         5

# Custom vars
version:          0.0.9

github:
  repo:           https://github.com/poole/hyde
  googleAnalytics: UA-120466923-1


